# Generated by Django 5.0.2 on 2024-02-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(upload_to='tags'),
        ),
    ]
